#!/bin/bash

# --------------------------------------
# load_workouts.sh
# Full pipeline runner for workouts.csv
# --------------------------------------

# Usage check
if [ -z "$1" ]; then
  echo "Usage: $0 /path/to/workouts.csv"
  exit 1
fi

CSV_FILE="$1"

if [ ! -f "$CSV_FILE" ]; then
  echo "ERROR: File not found: $CSV_FILE"
  exit 1
fi

# --------------------------
# SnowSQL connection profile
# Update this if needed
# --------------------------
CONN="training_conn"

echo "===================================="
echo " Uploading file to Snowflake stage..."
echo "===================================="

snowsql -c $CONN -q "
  PUT file://$CSV_FILE @TRAINING_DB.BRONZE.WORKOUT_STAGE AUTO_COMPRESS=FALSE;
"

if [ $? -ne 0 ]; then
  echo "ERROR during PUT. Aborting."
  exit 1
fi

echo
echo "===================================="
echo " Running full SQL pipeline..."
echo "===================================="

snowsql -c $CONN -q "
-- 1) Context
USE DATABASE TRAINING_DB;
USE SCHEMA BRONZE;

-- 2) Clear BRONZE table
TRUNCATE TABLE IF EXISTS BRONZE.WORKOUT_LOG_RAW;

-- 3) Load CSV into BRONZE
COPY INTO BRONZE.WORKOUT_LOG_RAW
FROM @BRONZE.WORKOUT_STAGE
FILE_FORMAT = (FORMAT_NAME = BRONZE.WORKOUT_CSV_FORMAT)
ON_ERROR = 'CONTINUE';

-- 4) Move to SILVER
USE SCHEMA SILVER;

-- 5) Clear and rebuild ledger
TRUNCATE TABLE IF EXISTS SILVER.WORKOUT_LOG_CLEANSED;

INSERT INTO SILVER.WORKOUT_LOG_CLEANSED
SELECT 
    TITLE,
    TRY_TO_TIMESTAMP_NTZ(START_TIME, 'DD MON YYYY, HH24:MI') AS START_TIME,
    TRY_TO_TIMESTAMP_NTZ(END_TIME, 'DD MON YYYY, HH24:MI') AS END_TIME,
    DESCRIPTION,
    EXERCISE_TITLE,
    SUPERSET_ID,
    EXERCISE_NOTES,
    SET_INDEX,
    SET_TYPE,
    WEIGHT_KG,
    REPS,
    DISTANCE_KM,
    DURATION_SECONDS,
    RPE,
    CURRENT_TIMESTAMP() AS INGESTED_AT
FROM TRAINING_DB.BRONZE.WORKOUT_LOG_RAW t;

-- 6) Rebuild EXERCISES table
TRUNCATE TABLE IF EXISTS SILVER.EXERCISES;

INSERT INTO SILVER.EXERCISES (EXERCISE_ID, EXERCISE_TITLE)
SELECT DISTINCT
  MD5(UPPER(TRIM(EXERCISE_TITLE))) AS EXERCISE_ID,
  EXERCISE_TITLE
FROM SILVER.WORKOUT_LOG_CLEANSED
WHERE EXERCISE_TITLE IS NOT NULL;

-- 7) Rebuild WORKOUTS table
TRUNCATE TABLE IF EXISTS SILVER.WORKOUTS;

INSERT INTO SILVER.WORKOUTS (WORKOUT_ID, TITLE, START_TIME, END_TIME, DESCRIPTION)
SELECT DISTINCT
  MD5(CONCAT(
    COALESCE(START_TIME::VARCHAR, ''),
    '||',
    COALESCE(UPPER(TRIM(TITLE)), ''),
    '||',
    COALESCE(END_TIME::VARCHAR, '')
  )) AS WORKOUT_ID,
  TITLE,
  START_TIME,
  END_TIME,
  DESCRIPTION
FROM SILVER.WORKOUT_LOG_CLEANSED
WHERE START_TIME IS NOT NULL AND TITLE IS NOT NULL;

-- 8) Rebuild WORKOUT_EXERCISES table
TRUNCATE TABLE IF EXISTS SILVER.WORKOUT_EXERCISES;

INSERT INTO SILVER.WORKOUT_EXERCISES (WORKOUT_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, SUPERSET_ID, EXERCISE_NOTES)
SELECT DISTINCT
  MD5(CONCAT(
    COALESCE(START_TIME::VARCHAR, ''),
    '||',
    COALESCE(UPPER(TRIM(TITLE)), ''),
    '||',
    COALESCE(END_TIME::VARCHAR, ''),
    '||',
    COALESCE(UPPER(TRIM(EXERCISE_TITLE)), ''),
    '||',
    COALESCE(SUPERSET_ID::VARCHAR, '')
  )) AS WORKOUT_EXERCISE_ID,
  MD5(CONCAT(
    COALESCE(START_TIME::VARCHAR, ''),
    '||',
    COALESCE(UPPER(TRIM(TITLE)), ''),
    '||',
    COALESCE(END_TIME::VARCHAR, '')
  )) AS WORKOUT_ID,
  MD5(UPPER(TRIM(EXERCISE_TITLE))) AS EXERCISE_ID,
  SUPERSET_ID,
  EXERCISE_NOTES
FROM SILVER.WORKOUT_LOG_CLEANSED
WHERE START_TIME IS NOT NULL AND TITLE IS NOT NULL AND EXERCISE_TITLE IS NOT NULL;

-- 9) Rebuild SETS table
TRUNCATE TABLE IF EXISTS SILVER.SETS;

INSERT INTO SILVER.SETS (
    SET_ID,
    WORKOUT_EXERCISE_ID,
    SET_INDEX,
    SET_TYPE,
    WEIGHT_KG,
    REPS,
    DISTANCE_KM,
    DURATION_SECONDS,
    RPE
)
SELECT
    MD5(CONCAT(we.WORKOUT_EXERCISE_ID, '||', COALESCE(wl.SET_INDEX::VARCHAR,''))) AS SET_ID,
    we.WORKOUT_EXERCISE_ID,
    wl.SET_INDEX,
    wl.SET_TYPE,
    wl.WEIGHT_KG,
    wl.REPS,
    wl.DISTANCE_KM,
    wl.DURATION_SECONDS,
    wl.RPE
FROM SILVER.WORKOUT_LOG_CLEANSED wl
JOIN SILVER.WORKOUTS w
    ON w.TITLE = wl.TITLE
   AND w.START_TIME = wl.START_TIME
JOIN SILVER.EXERCISES e
    ON LOWER(e.EXERCISE_TITLE) = LOWER(wl.EXERCISE_TITLE)
JOIN SILVER.WORKOUT_EXERCISES we
    ON we.WORKOUT_ID = w.WORKOUT_ID
   AND we.EXERCISE_ID = e.EXERCISE_ID
   AND COALESCE(we.SUPERSET_ID, '') = COALESCE(wl.SUPERSET_ID, '');

-- Summary check
SELECT
  (SELECT COUNT(*) FROM BRONZE.WORKOUT_LOG_RAW) AS bronze_rows,
  (SELECT COUNT(*) FROM SILVER.WORKOUT_LOG_CLEANSED) AS ledger_rows,
  (SELECT COUNT(*) FROM SILVER.EXERCISES) AS exercises,
  (SELECT COUNT(*) FROM SILVER.WORKOUTS) AS workouts,
  (SELECT COUNT(*) FROM SILVER.WORKOUT_EXERCISES) AS workout_exercises,
  (SELECT COUNT(*) FROM SILVER.SETS) AS sets;
"

echo
echo "===================================="
echo " Pipeline complete!"
echo "===================================="